# Assignment 05
 
 Introduction to Numerical Problem Solving, Spring 2017
 
 24.3.2017, Ali Bahrami
 
 Helsinki Metropolia University of Applied Sciences

### General import for the exercises 

In [50]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import *
from numpy import *
from pprint import pprint
from scipy.linalg import lu_factor, lu_solve, lu, solve,inv, det
from copy import copy, deepcopy

## 3.
The import for using the functions is done above.  Now we try to solve matrix.

In [14]:


A= array([1,4,1,1,6,-1,2,-1,2]).reshape(3,3)
b=array([7,13,5])
TL=array([0,0,0,1,0,0,1,1,0]).reshape(3,3)
LUP=array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
TU=array([1,1,1,0,1,1,0,0,1]).reshape(3,3)

LU=lu_factor(A)
X=lu_solve(LU,b) 
L=TL*LU[0]+LUP
U=TU*LU[0]

P2, L2, U2=lu(A)
y=solve(dot(P2,L2),b)
x=solve(U2,y)
print("L value based on results from lu_factor function:")
pprint(L)
print("L value based on results from lu function:")
pprint(L2)
print("U value based on results from lu_factor function:")
pprint(U)
print("U value based on results from lu function:")
pprint(U2)
print("A is: ")
pprint(A)
print("Solution based on solve and lu functions of scipy:")
pprint(x)
print("Solution based on lu_solve and lu_factor functions of scipy:")
pprint(X)




L value based on results from lu_factor function:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.5       ,  0.69230769,  1.        ]])
L value based on results from lu function:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.5       ,  0.69230769,  1.        ]])
U value based on results from lu_factor function:
array([[ 2.        , -1.        ,  2.        ],
       [ 0.        ,  6.5       , -2.        ],
       [ 0.        ,  0.        ,  1.38461538]])
U value based on results from lu function:
array([[ 2.        , -1.        ,  2.        ],
       [ 0.        ,  6.5       , -2.        ],
       [ 0.        ,  0.        ,  1.38461538]])
A is: 
array([[ 1,  4,  1],
       [ 1,  6, -1],
       [ 2, -1,  2]])
Solution based on solve and lu functions of scipy:
array([ 5.,  1., -2.])
Solution based on lu_solve and lu_factor functions of scipy:
array([ 5.,  1., -2.])


### 5.
For invertion we define a simple function.


In [15]:
def invert_matrix1(A):
    return inv(A)


A=np.array([
        [5,-3,-1,0],
        [-2,1,1,1],
        [3,-5,1,2],
        [0,8,-4,-3.0]
        ])
B=np.array([
        [1,3,-9,6,4],
        [2,-1,6,7,1],
        [3,2,-3,15,5],
        [8,-1,1,4,2],
        [11,1,-2,18,7.0]
        ])

A_inverse=(invert_matrix1(A))
B_inverse=(invert_matrix1(B))
print("Determinant A is ",det(A))
print("Determinant B is ",det(B))
print("Epsilon is",np.finfo(float).eps)
print("I calculation for A")
pprint(around(A_inverse.dot(A),8))
print("I calculation for B")
pprint(around(B_inverse.dot(B),8))


Determinant A is  15.999999999999991
Determinant B is  2.9187763317395335e-13
Epsilon is 2.22044604925e-16
I calculation for A
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [-0.,  0.,  0.,  1.]])
I calculation for B
array([[  2.5 ,   0.25,  -1.  ,  -1.  ,   2.5 ],
       [ -2.  ,   4.  , -12.  , -12.  ,   6.  ],
       [  2.  ,   0.  ,   0.  ,   0.  ,   2.  ],
       [  0.  ,   0.  ,   0.  ,   1.  ,   0.  ],
       [  2.  ,   0.  ,   0.  ,  -4.  ,   2.  ]])


### Why the calculation is not correct?
The determinant of matrix B is zero, therfore such a matrix should not be invertible. However, the determinant of B is not exactly equal to zero, as the determinant is calculated by float binary pointing system. The result is close to system's epsilon. Therfore the method which uses numpy inv function, will calculate the inversion. To solve this problem the following condition should be added.

In [9]:
if linalg.cond(B) < 1/sys.float_info.epsilon:
    I = linalg.inv(B)
else:
    print("B is not invertible")


B is not invertible


### Better Solution
What happens in the code is that we compute the condition of matrix before calculating inversion. As a result the correct calculation should be as follows.


In [16]:
def invert_matrix1(A):
    return inv(A)
def valid_matrix1(A):
    if linalg.cond(A) < 1/sys.float_info.epsilon :
        return True
    else:
        return False

A=np.array([
        [5,-3,-1,0],
        [-2,1,1,1],
        [3,-5,1,2],
        [0,8,-4,-3.0]
        ])
B=np.array([
        [1,3,-9,6,4],
        [2,-1,6,7,1],
        [3,2,-3,15,5],
        [8,-1,1,4,2],
        [11,1,-2,18,7.0]
        ])
print("For A")
pprint(A)
print("And for B")
pprint(B)

if(valid_matrix1(A)):
    A_inverse=(invert_matrix1(A))
    print("Determinant A is ",det(A))
    print("I for A is")
    pprint(around(A_inverse.dot(A),8))    
else:
    print("A is not invertible")

if(valid_matrix1(B)):
    B_inverse=(invert_matrix1(B))
    print("Determinant B is ",det(B))
    print("I for B is")
    pprint(around(B_inverse.dot(B),8))
else:
    print("B is not invertible")


For A
array([[ 5., -3., -1.,  0.],
       [-2.,  1.,  1.,  1.],
       [ 3., -5.,  1.,  2.],
       [ 0.,  8., -4., -3.]])
And for B
array([[  1.,   3.,  -9.,   6.,   4.],
       [  2.,  -1.,   6.,   7.,   1.],
       [  3.,   2.,  -3.,  15.,   5.],
       [  8.,  -1.,   1.,   4.,   2.],
       [ 11.,   1.,  -2.,  18.,   7.]])
Determinant A is  15.999999999999991
I for A is
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [-0.,  0.,  0.,  1.]])
B is not invertible


### 9.
We define a function for calculating the solution of Ax=b based on gaussSeidel with weights.


In [110]:
from decimal import *

def gaussSeidel(A, b,w,maxiteration):
    n = len(b)
    x0 = array([0, 0, 0,0.0])
    x0=np.around(x0,decimals=2)
    eps=sys.float_info.epsilon
    solved=False
    for i in range(n):
        x0[i]=b[i]/A[i,i]
    x = deepcopy(x0)
    xold=deepcopy(x0)
    xoldest=copy(x0)
        
    for k in range(maxiteration):
        xoldest = deepcopy(xold)
        xold = deepcopy(x)
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s = s + A[i, j]*x[j]
            x[i] = w/A[i, i]*(b[i] - s)+ (1-w)*x[i-1]
        #if(abs((xold-x).all())<eps):
        #    solved=True
        #    break
        #print(abs(xoldest-xold).any())   
        #elif ((xoldest-xold).any()>threshold):
         #   print("out")
    if(not solved):
        print("not enumerated enough")
    print(k,"Xpldes {:0.30f}".format(xoldest[0]))
    print(k,"xOLD   {:0.30f}".format(xold[0]))
        
    return x

In [112]:
A = array([4, -1, 0, 0, -1, 4, -1, 0, 0,-1,4,-1,0,0,-1,3.0]).reshape(4, 4)
#A = np.around(A,decimals=2)
b = array([15, 10, 10,10.0])
#b= np.around(b,decimals=2)
maxiter=100
w=1.10
x=gaussSeidel(A,b,w,maxiter)

LU=lu_factor(A)
X=lu_solve(LU,b) 
#x=np.around(x,decimals=2)
print("x based on gaussSeidel ",x)
print("x based on lu_solve",X)

print("A",A)
print("b",b)

print("Ax-b=",A.dot(x)-b)

not enumerated enough
99 Xpldes 5.000000000000000000000000000000
99 xOLD   5.000000000000000000000000000000
x based on gaussSeidel  [ 5.  5.  5.  5.]
x based on lu_solve [ 5.  5.  5.  5.]
A [[ 4. -1.  0.  0.]
 [-1.  4. -1.  0.]
 [ 0. -1.  4. -1.]
 [ 0.  0. -1.  3.]]
b [ 15.  10.  10.  10.]
Ax-b= [ 0.  0.  0.  0.]


### Note
The formula 2.35 in the course is not correct. 
The correct relaxation is calculated by  x[i]= w/( formula2.34 )+ (1-w) * x[i-1]